In [74]:
import pandas as pd
import numpy as np

In [75]:
df = pd.read_csv("Data/hotel_bookings.csv")
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [76]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [77]:
df['is_canceled'].value_counts()

0    75166
1    44224
Name: is_canceled, dtype: int64

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

In [79]:
# Eleccion de las caracteristicas que hemos considerado relevantes para el problema. 
# Las descripciones detalladas de cada caracteristica estan en el archivo .txt adjunto. 

columnas = [
    "hotel",
    "is_canceled",
    "lead_time",
    "arrival_date_year",
    "arrival_date_month",
    "arrival_date_day_of_month",
    "stays_in_weekend_nights",
    "stays_in_week_nights",
    "adults",
    "children",
    "babies",
    "meal",
    "country",
    "market_segment",
    "distribution_channel",
    "is_repeated_guest",
    "previous_cancellations",
    "previous_bookings_not_canceled",
    "booking_changes",
    "deposit_type",
    "days_in_waiting_list",
    "customer_type",
    "total_of_special_requests",
    "reservation_status_date"
]

In [80]:
df = df[columnas]
df.isna().sum()

hotel                               0
is_canceled                         0
lead_time                           0
arrival_date_year                   0
arrival_date_month                  0
arrival_date_day_of_month           0
stays_in_weekend_nights             0
stays_in_week_nights                0
adults                              0
children                            4
babies                              0
meal                                0
country                           488
market_segment                      0
distribution_channel                0
is_repeated_guest                   0
previous_cancellations              0
previous_bookings_not_canceled      0
booking_changes                     0
deposit_type                        0
days_in_waiting_list                0
customer_type                       0
total_of_special_requests           0
reservation_status_date             0
dtype: int64

In [81]:
df.shape

(119390, 24)

In [82]:
# Eliminamos las filas que contienen NaNs, ya que son muy pocas comparadas con el total de filas. 
df.dropna(axis=0,inplace=True)

C:\Users\mrtfo\AppData\Local\Temp\ipykernel_6372\2739904053.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(axis=0,inplace=True)

In [83]:
df.shape

(118898, 24)

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 118898 entries, 0 to 119389
Data columns (total 24 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           118898 non-null  object
 1   is_canceled                     118898 non-null  int64
 2   lead_time                       118898 non-null  int64
 3   arrival_date_year               118898 non-null  int64
 4   arrival_date_month              118898 non-null  object
 5   arrival_date_day_of_month       118898 non-null  int64
 6   stays_in_weekend_nights         118898 non-null  int64
 7   stays_in_week_nights            118898 non-null  int64
 8   adults                          118898 non-null  int64
 9   children                        118898 non-null  float64
 10  babies                          118898 non-null  int64
 11  meal                            118898 non-null  object
 12  country                         118898 non-null  object
 13  market_segment                  118898 non-null  object
 14  distribution_channel            118898 non-null  object
 15  is_repeated_guest               118898 non-null  int64
 16  previous_cancellations          118898 non-null  int64
 17  previous_bookings_not_canceled  118898 non-null  int64
 18  booking_changes                 118898 non-null  int64
 19  deposit_type                    118898 non-null  object
 20  days_in_waiting_list            118898 non-null  int64
 21  customer_type                   118898 non-null  object
 22  total_of_special_requests       118898 non-null  int64
 23  reservation_status_date         118898 non-null  object
dtypes: float64(1), int64(14), object(9)
memory usage: 22.7+ MB

A continuacion, consultamos todas las categorias que tenemos en cada característica categórica, para ver si podemos reducirlas y poder tener un modelo de ML más óptimo.

In [85]:
df['customer_type'].value_counts()

Transient          89174
Transient-Party    25078
Contract            4076
Group                570
Name: customer_type, dtype: int64

In [86]:
df['deposit_type'].value_counts()

No Deposit    104163
Non Refund     14573
Refundable       162
Name: deposit_type, dtype: int64

In [87]:
df['distribution_channel'].value_counts()

TA/TO        97730
Direct       14483
Corporate     6491
GDS            193
Undefined        1
Name: distribution_channel, dtype: int64

In [88]:
# Asignamos la moda al único valor indefinido.
df['distribution_channel'] = df['distribution_channel'].apply(lambda x: 'TA/TO' if x == 'Undefined' else x)
df['distribution_channel'].value_counts()

C:\Users\mrtfo\AppData\Local\Temp\ipykernel_6372\152945679.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['distribution_channel'] = df['distribution_channel'].apply(lambda x: 'TA/TO' if x == 'Undefined' else x)

TA/TO        97731
Direct       14483
Corporate     6491
GDS            193
Name: distribution_channel, dtype: int64

In [89]:
df['market_segment'].value_counts()

Online TA        56402
Offline TA/TO    24160
Groups           19806
Direct           12448
Corporate         5111
Complementary      734
Aviation           237
Name: market_segment, dtype: int64

In [90]:
# Agrupamos las reservas via agencia de viaje offline y online en una misma categoria.
df['market_segment'] = df['market_segment'].apply(lambda x: 'TA/TO' if x in ['Online TA', 'Offline TA/TO'] else x)
df['market_segment'].value_counts()

C:\Users\mrtfo\AppData\Local\Temp\ipykernel_6372\93595267.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['market_segment'] = df['market_segment'].apply(lambda x: 'TA/TO' if x in ['Online TA', 'Offline TA/TO'] else x)

TA/TO            80562
Groups           19806
Direct           12448
Corporate         5111
Complementary      734
Aviation           237
Name: market_segment, dtype: int64

In [91]:
df['meal'].value_counts()

BB           91863
HB           14434
SC           10638
Undefined     1165
FB             798
Name: meal, dtype: int64

In [92]:
# Undefined y SC significan que no se contrató comida incluida
sin_comida = ['Undefined', 'SC']
df['meal'] = df['meal'].apply(lambda x: x if x not in sin_comida else 'No_meal')
df['meal'].value_counts()

C:\Users\mrtfo\AppData\Local\Temp\ipykernel_6372\3449350740.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['meal'] = df['meal'].apply(lambda x: x if x not in sin_comida else 'No_meal')

BB         91863
HB         14434
No_meal    11803
FB           798
Name: meal, dtype: int64

In [93]:
# Nos quedamos solo con el top5 de paises de origen mas comunes entre los 177, el resto se agrupan en una categoria "otros"
paises_comunes = df['country'].value_counts().head(5).index
df['country'] = df['country'].apply(lambda x: x if x in paises_comunes else 'otros')
df['country'].value_counts()

C:\Users\mrtfo\AppData\Local\Temp\ipykernel_6372\2380653426.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['country'] = df['country'].apply(lambda x: x if x in paises_comunes else 'otros')

PRT      48586
otros    31913
GBR      12129
FRA      10415
ESP       8568
DEU       7287
Name: country, dtype: int64

In [94]:
# Cambiamos el nombre de los meses por su numero
meses = {
    'January': 1,
    'February': 2,
    'March': 3,
    'April': 4,
    'May': 5,
    'June': 6,
    'July': 7,
    'August': 8,
    'September': 9,
    'October': 10,
    'November': 11,
    'December': 12
}

df['arrival_date_month'] = df['arrival_date_month'].map(meses)

C:\Users\mrtfo\AppData\Local\Temp\ipykernel_6372\2658925585.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['arrival_date_month'] = df['arrival_date_month'].map(meses)

In [95]:
# Creamos una columna nueva con la fecha de llegada al hotel completa
df['arrival_date'] = pd.to_datetime(df.rename(columns={'arrival_date_year': 'year', 'arrival_date_month': 'month', 'arrival_date_day_of_month': 'day'})[['year', 'month', 'day']])

C:\Users\mrtfo\AppData\Local\Temp\ipykernel_6372\900626620.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['arrival_date'] = pd.to_datetime(df.rename(columns={'arrival_date_year': 'year', 'arrival_date_month': 'month', 'arrival_date_day_of_month': 'day'})[['year', 'month', 'day']])

In [96]:
# Eliminamos las columnas de año, mes y dia separados

df.drop(columns=['arrival_date_year','arrival_date_month','arrival_date_day_of_month'], inplace=True)

C:\Users\mrtfo\AppData\Local\Temp\ipykernel_6372\3997300504.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['arrival_date_year','arrival_date_month','arrival_date_day_of_month'], inplace=True)

In [97]:
# Pasamos la fecha de ultima modificacion de la resera a formato datetime para tener las dos fechas en el mismmo formato
df['reservation_status_date'] = pd.to_datetime(df['reservation_status_date'])

C:\Users\mrtfo\AppData\Local\Temp\ipykernel_6372\1267756437.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reservation_status_date'] = pd.to_datetime(df['reservation_status_date'])

In [98]:
df.shape

(118898, 22)

In [99]:
df.to_csv('Data/hotel_bookings_clean.csv', index=False)

In [100]:
df.iloc[10]

hotel                                    Resort Hotel
is_canceled                                         1
lead_time                                          23
stays_in_weekend_nights                             0
stays_in_week_nights                                4
adults                                              2
children                                          0.0
babies                                              0
meal                                               BB
country                                           PRT
market_segment                                  TA/TO
distribution_channel                            TA/TO
is_repeated_guest                                   0
previous_cancellations                              0
previous_bookings_not_canceled                      0
booking_changes                                     0
deposit_type                               No Deposit
days_in_waiting_list                                0
customer_type                               Transient
total_of_special_requests                           0
reservation_status_date           2015-06-23 00:00:00
arrival_date                      2015-07-01 00:00:00
Name: 10, dtype: object

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 118898 entries, 0 to 119389
Data columns (total 22 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           118898 non-null  object
 1   is_canceled                     118898 non-null  int64
 2   lead_time                       118898 non-null  int64
 3   stays_in_weekend_nights         118898 non-null  int64
 4   stays_in_week_nights            118898 non-null  int64
 5   adults                          118898 non-null  int64
 6   children                        118898 non-null  float64
 7   babies                          118898 non-null  int64
 8   meal                            118898 non-null  object
 9   country                         118898 non-null  object
 10  market_segment                  118898 non-null  object
 11  distribution_channel            118898 non-null  object
 12  is_repeated_guest               118898 non-null  int64
 13  previous_cancellations          118898 non-null  int64
 14  previous_bookings_not_canceled  118898 non-null  int64
 15  booking_changes                 118898 non-null  int64
 16  deposit_type                    118898 non-null  object
 17  days_in_waiting_list            118898 non-null  int64
 18  customer_type                   118898 non-null  object
 19  total_of_special_requests       118898 non-null  int64
 20  reservation_status_date         118898 non-null  datetime64[ns]
 21  arrival_date                    118898 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(12), object(7)
memory usage: 20.9+ MB

In [102]:
# Comprovamos que la proporcion de cancelaciones es la misma respecto al df original
df['is_canceled'].value_counts()

0    74745
1    44153
Name: is_canceled, dtype: int64

In [103]:
meteolisboa = pd.read_csv('Data/Datostiempolisboa.csv')
meteoalgarve = pd.read_csv('Data/Datostiempoalgarve.csv')

In [104]:
meteolisboa.columns

Index(['name', 'datetime', 'tempmax', 'tempmin', 'temp', 'feelslikemax',
       'feelslikemin', 'feelslike', 'dew', 'humidity', 'precip', 'precipprob',
       'precipcover', 'preciptype', 'snow', 'snowdepth', 'windgust',
       'windspeed', 'winddir', 'sealevelpressure', 'cloudcover', 'visibility',
       'solarradiation', 'solarenergy', 'uvindex', 'severerisk', 'sunrise',
       'sunset', 'moonphase', 'conditions', 'description', 'icon', 'stations'],
      dtype='object')

In [105]:
# Eleccion de las caracteristicas relevantes. 
# Nos hemos quedado solo con las caracteristicas que nos puede dar una prediccion del tiempo, hemos eliminado todas las medidas posteriores.
columnas = [
    "name",
    "datetime",
    "tempmax", 
    "tempmin",
    "temp",
    "precip",
    "precipprob",
    "windgust",
    "windspeed",
    "conditions",
    "cloudcover"
]

In [106]:
meteolisboa = meteolisboa[columnas]
meteoalgarve = meteoalgarve[columnas]

In [107]:
# Modificamos el nombre de la ciudad por el hotel y tener la misma columna que en el otro dataset.
# Lo podemos hacer porque el City Hotel siempre está en Lisboa y el Resort Hotel siempre está en el Algarve. 

meteolisboa.rename(columns={"name":"hotel"}, inplace=True)
meteolisboa["hotel"].replace("Lisbon", "City Hotel", inplace=True)
meteoalgarve.rename(columns={"name":"hotel"}, inplace=True)
meteoalgarve["hotel"].replace("Albufeira", "Resort Hotel", inplace=True)

In [108]:
# Reemplazamos los NaNs por 0, ya que en ese caso la absencia de datos significa que no habia ráfagas de viento.
meteolisboa["windgust"].fillna(0, inplace=True)
meteoalgarve["windgust"].fillna(0, inplace=True)

In [109]:
print(meteoalgarve.isna().sum(), meteolisboa.isna().sum())

hotel         0
datetime      0
tempmax       0
tempmin       0
temp          0
precip        0
precipprob    0
windgust      0
windspeed     0
conditions    0
cloudcover    0
dtype: int64 hotel         0
datetime      0
tempmax       0
tempmin       0
temp          0
precip        0
precipprob    0
windgust      0
windspeed     0
conditions    0
cloudcover    0
dtype: int64

In [110]:
meteolisboa['datetime'] = pd.to_datetime(meteolisboa["datetime"])
meteoalgarve['datetime'] = pd.to_datetime(meteoalgarve["datetime"])

In [111]:
# Comprobacion que las categorias de los dos datasets coinciden
meteolisboa['conditions'].value_counts()

Partially cloudy          368
Rain, Partially cloudy    245
Clear                     167
Rain                        5
Rain, Overcast              5
Overcast                    3
Name: conditions, dtype: int64

In [112]:
meteoalgarve['conditions'].value_counts()

Partially cloudy          327
Clear                     302
Rain, Partially cloudy    158
Rain                        4
Overcast                    2
Name: conditions, dtype: int64

In [113]:
meteoalgarve.to_csv('Data/meteo_algarve_clean.csv', index=False)
meteolisboa.to_csv('Data/meteo_lisboa_clean.csv', index=False)

In [114]:
meteoalgarve.iloc[101]

hotel                   Resort Hotel
datetime         2015-10-10 00:00:00
tempmax                         19.7
tempmin                         17.2
temp                            18.5
precip                        10.577
precipprob                       100
windgust                        39.6
windspeed                       30.3
conditions    Rain, Partially cloudy
cloudcover                      71.4
Name: 101, dtype: object

## Proves vàries

In [115]:
cancelaciones = df[df["is_canceled"] == 1]
cancelaciones

,hotel,is_canceled,lead_time,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,...,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,deposit_type,days_in_waiting_list,customer_type,total_of_special_requests,reservation_status_date,arrival_date
8,Resort Hotel,1,85,0,3,2,0.0,0,BB,PRT,...,0,0,0,0,No Deposit,0,Transient,1,2015-05-06,2015-07-01
9,Resort Hotel,1,75,0,3,2,0.0,0,HB,PRT,...,0,0,0,0,No Deposit,0,Transient,0,2015-04-22,2015-07-01
10,Resort Hotel,1,23,0,4,2,0.0,0,BB,PRT,...,0,0,0,0,No Deposit,0,Transient,0,2015-06-23,2015-07-01
27,Resort Hotel,1,60,2,5,2,0.0,0,BB,PRT,...,0,0,0,0,No Deposit,0,Transient,2,2015-05-11,2015-07-01
32,Resort Hotel,1,96,2,8,2,0.0,0,BB,PRT,...,0,0,0,0,No Deposit,0,Transient,2,2015-05-29,2015-07-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110280,City Hotel,1,132,0,0,0,0.0,0,BB,FRA,...,0,0,0,1,No Deposit,0,Transient,3,2017-04-25,2017-04-25
111355,City Hotel,1,4,1,0,1,0.0,0,BB,PRT,...,1,0,4,0,No Deposit,0,Transient,0,2017-06-05,2017-06-05
111924,City Hotel,1,7,0,1,1,0.0,0,BB,PRT,...,1,0,1,0,No Deposit,0,Transient,0,2017-05-31,2017-05-31
111925,City Hotel,1,6,1,0,1,0.0,0,BB,PRT,...,1,1,1,0,No Deposit,0,Transient,0,2017-07-17,2017-07-17
117295,City Hotel,1,0,0,2,1,0.0,0,BB,PRT,...,1,0,0,0,No Deposit,0,Transient,1,2017-08-02,2017-08-02

In [116]:
diferencia_mas_15_dias = cancelaciones[(cancelaciones['arrival_date'] - cancelaciones['reservation_status_date'] > pd.Timedelta(days=15))]
diferencia_mas_15_dias

,hotel,is_canceled,lead_time,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,...,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,deposit_type,days_in_waiting_list,customer_type,total_of_special_requests,reservation_status_date,arrival_date
8,Resort Hotel,1,85,0,3,2,0.0,0,BB,PRT,...,0,0,0,0,No Deposit,0,Transient,1,2015-05-06,2015-07-01
9,Resort Hotel,1,75,0,3,2,0.0,0,HB,PRT,...,0,0,0,0,No Deposit,0,Transient,0,2015-04-22,2015-07-01
27,Resort Hotel,1,60,2,5,2,0.0,0,BB,PRT,...,0,0,0,0,No Deposit,0,Transient,2,2015-05-11,2015-07-01
32,Resort Hotel,1,96,2,8,2,0.0,0,BB,PRT,...,0,0,0,0,No Deposit,0,Transient,2,2015-05-29,2015-07-01
34,Resort Hotel,1,45,1,3,3,0.0,0,BB,PRT,...,0,0,0,0,No Deposit,0,Transient,1,2015-05-19,2015-07-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87687,City Hotel,1,315,0,1,2,0.0,0,BB,PRT,...,0,2,4,0,No Deposit,0,Transient-Party,1,2016-11-07,2016-11-25
87688,City Hotel,1,312,0,1,1,1.0,0,BB,PRT,...,0,2,4,0,No Deposit,0,Transient-Party,1,2016-11-07,2016-11-25
89645,City Hotel,1,194,0,3,2,0.0,0,BB,PRT,...,1,1,1,0,No Deposit,0,Transient,0,2016-12-27,2017-05-25
92951,City Hotel,1,54,1,0,1,0.0,0,BB,PRT,...,1,1,10,0,No Deposit,0,Transient,0,2017-01-31,2017-03-26
92963,City Hotel,1,54,1,0,1,0.0,0,BB,PRT,...,1,1,10,0,No Deposit,0,Transient,0,2017-01-31,2017-03-26

In [117]:
diferencia_menos_15_dias_2017 = cancelaciones[(cancelaciones['arrival_date'] - cancelaciones['reservation_status_date'] <= pd.Timedelta(days=15)) & (df['arrival_date'].dt.year == 2017)]
diferencia_menos_15_dias_2017

C:\Users\mrtfo\AppData\Local\Temp\ipykernel_6372\2380953126.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  diferencia_menos_15_dias_2017 = cancelaciones[(cancelaciones['arrival_date'] - cancelaciones['reservation_status_date'] <= pd.Timedelta(days=15)) & (df['arrival_date'].dt.year == 2017)]

,hotel,is_canceled,lead_time,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,...,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,deposit_type,days_in_waiting_list,customer_type,total_of_special_requests,reservation_status_date,arrival_date
9787,Resort Hotel,1,143,1,1,2,0.0,0,BB,otros,...,0,0,0,1,No Deposit,0,Transient,1,2016-12-24,2017-01-02
9788,Resort Hotel,1,89,1,3,2,0.0,0,BB,GBR,...,0,0,0,0,No Deposit,0,Transient,1,2017-01-02,2017-01-02
9795,Resort Hotel,1,20,1,5,2,1.0,1,BB,FRA,...,0,0,0,1,No Deposit,0,Transient,1,2016-12-19,2017-01-02
9797,Resort Hotel,1,36,3,7,2,0.0,0,BB,GBR,...,0,0,0,0,No Deposit,0,Transient,2,2016-12-22,2017-01-02
9799,Resort Hotel,1,46,0,3,2,1.0,0,BB,otros,...,0,0,0,0,No Deposit,0,Transient,0,2016-12-23,2017-01-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110280,City Hotel,1,132,0,0,0,0.0,0,BB,FRA,...,0,0,0,1,No Deposit,0,Transient,3,2017-04-25,2017-04-25
111355,City Hotel,1,4,1,0,1,0.0,0,BB,PRT,...,1,0,4,0,No Deposit,0,Transient,0,2017-06-05,2017-06-05
111924,City Hotel,1,7,0,1,1,0.0,0,BB,PRT,...,1,0,1,0,No Deposit,0,Transient,0,2017-05-31,2017-05-31
111925,City Hotel,1,6,1,0,1,0.0,0,BB,PRT,...,1,1,1,0,No Deposit,0,Transient,0,2017-07-17,2017-07-17
117295,City Hotel,1,0,0,2,1,0.0,0,BB,PRT,...,1,0,0,0,No Deposit,0,Transient,1,2017-08-02,2017-08-02

In [118]:
diferencia_menos_7_dias = cancelaciones[(cancelaciones['arrival_date'] - cancelaciones['reservation_status_date'] <= pd.Timedelta(days=7)) & ((cancelaciones['arrival_date'].dt.year == 2015) | (cancelaciones['arrival_date'].dt.year ==2016))]

In [119]:
diferencia_menos_7_dias

,hotel,is_canceled,lead_time,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,...,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,deposit_type,days_in_waiting_list,customer_type,total_of_special_requests,reservation_status_date,arrival_date
64,Resort Hotel,1,3,0,3,2,0.0,0,HB,PRT,...,0,0,0,0,No Deposit,0,Transient,2,2015-06-29,2015-07-02
70,Resort Hotel,1,62,0,2,2,0.0,0,BB,PRT,...,0,0,0,0,No Deposit,0,Transient,1,2015-07-03,2015-07-03
95,Resort Hotel,1,72,0,2,2,0.0,0,BB,PRT,...,0,0,0,0,No Deposit,0,Transient,1,2015-06-29,2015-07-03
122,Resort Hotel,1,36,0,1,1,0.0,0,BB,PRT,...,0,0,0,1,No Deposit,0,Transient,0,2015-07-04,2015-07-04
132,Resort Hotel,1,5,1,0,2,0.0,0,BB,PRT,...,0,0,0,0,No Deposit,0,Transient,0,2015-07-01,2015-07-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94379,City Hotel,1,2,2,0,2,0.0,0,BB,PRT,...,1,1,5,0,No Deposit,0,Transient,4,2016-10-29,2016-10-30
95891,City Hotel,1,12,0,2,1,0.0,0,BB,PRT,...,1,0,4,0,No Deposit,0,Transient,1,2016-10-12,2016-10-12
97968,City Hotel,1,0,1,2,1,0.0,0,BB,PRT,...,1,0,1,0,No Deposit,0,Transient,0,2016-10-10,2016-10-10
98809,City Hotel,1,0,1,0,2,0.0,0,BB,PRT,...,1,0,1,0,No Deposit,0,Transient,2,2016-12-12,2016-12-12
98810,City Hotel,1,0,1,0,2,0.0,0,BB,PRT,...,1,0,1,0,No Deposit,0,Transient,2,2016-12-12,2016-12-12

In [120]:
no_cancelaciones = df[df["is_canceled"] == 0]
no_cancelaciones[no_cancelaciones['lead_time'] > 15]

,hotel,is_canceled,lead_time,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,...,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,deposit_type,days_in_waiting_list,customer_type,total_of_special_requests,reservation_status_date,arrival_date
0,Resort Hotel,0,342,0,0,2,0.0,0,BB,PRT,...,0,0,0,3,No Deposit,0,Transient,0,2015-07-01,2015-07-01
1,Resort Hotel,0,737,0,0,2,0.0,0,BB,PRT,...,0,0,0,4,No Deposit,0,Transient,0,2015-07-01,2015-07-01
11,Resort Hotel,0,35,0,4,2,0.0,0,HB,PRT,...,0,0,0,0,No Deposit,0,Transient,0,2015-07-05,2015-07-01
12,Resort Hotel,0,68,0,4,2,0.0,0,BB,otros,...,0,0,0,0,No Deposit,0,Transient,3,2015-07-05,2015-07-01
13,Resort Hotel,0,18,0,4,2,1.0,0,HB,ESP,...,0,0,0,1,No Deposit,0,Transient,1,2015-07-05,2015-07-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2,5,2,0.0,0,BB,otros,...,0,0,0,0,No Deposit,0,Transient,0,2017-09-06,2017-08-30
119386,City Hotel,0,102,2,5,3,0.0,0,BB,FRA,...,0,0,0,0,No Deposit,0,Transient,2,2017-09-07,2017-08-31
119387,City Hotel,0,34,2,5,2,0.0,0,BB,DEU,...,0,0,0,0,No Deposit,0,Transient,4,2017-09-07,2017-08-31
119388,City Hotel,0,109,2,5,2,0.0,0,BB,GBR,...,0,0,0,0,No Deposit,0,Transient,0,2017-09-07,2017-08-31
119389,City Hotel,0,205,2,7,2,0.0,0,HB,DEU,...,0,0,0,0,No Deposit,0,Transient,2,2017-09-07,2017-08-29

In [121]:
no_cancelaciones[no_cancelaciones['lead_time'] <= 15]

,hotel,is_canceled,lead_time,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,...,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,deposit_type,days_in_waiting_list,customer_type,total_of_special_requests,reservation_status_date,arrival_date
2,Resort Hotel,0,7,0,1,1,0.0,0,BB,GBR,...,0,0,0,0,No Deposit,0,Transient,0,2015-07-02,2015-07-01
3,Resort Hotel,0,13,0,1,1,0.0,0,BB,GBR,...,0,0,0,0,No Deposit,0,Transient,0,2015-07-02,2015-07-01
4,Resort Hotel,0,14,0,2,2,0.0,0,BB,GBR,...,0,0,0,0,No Deposit,0,Transient,1,2015-07-03,2015-07-01
5,Resort Hotel,0,14,0,2,2,0.0,0,BB,GBR,...,0,0,0,0,No Deposit,0,Transient,1,2015-07-03,2015-07-01
6,Resort Hotel,0,0,0,2,2,0.0,0,BB,PRT,...,0,0,0,0,No Deposit,0,Transient,0,2015-07-03,2015-07-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119270,City Hotel,0,0,0,3,2,1.0,0,BB,otros,...,0,0,0,1,No Deposit,0,Transient,2,2017-09-01,2017-08-29
119304,City Hotel,0,4,0,3,1,0.0,0,BB,otros,...,0,0,0,1,No Deposit,0,Transient,0,2017-09-02,2017-08-30
119312,City Hotel,0,4,0,3,2,0.0,0,No_meal,FRA,...,0,0,0,0,No Deposit,0,Transient,1,2017-09-03,2017-08-31
119316,City Hotel,0,1,0,3,2,0.0,0,BB,GBR,...,0,0,0,0,No Deposit,0,Transient,1,2017-09-03,2017-08-31
119324,City Hotel,0,8,0,3,2,0.0,0,BB,otros,...,0,0,0,0,No Deposit,0,Transient,0,2017-09-03,2017-08-31

In [126]:
mucha_antelacion = df[((df["is_canceled"] == 1) & (df['arrival_date'] - df['reservation_status_date'] > pd.Timedelta(days=15)) | ((df["is_canceled"] == 0) & (df['lead_time'] > 15)))]

In [127]:
mucha_antelacion

,hotel,is_canceled,lead_time,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,...,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,deposit_type,days_in_waiting_list,customer_type,total_of_special_requests,reservation_status_date,arrival_date
0,Resort Hotel,0,342,0,0,2,0.0,0,BB,PRT,...,0,0,0,3,No Deposit,0,Transient,0,2015-07-01,2015-07-01
1,Resort Hotel,0,737,0,0,2,0.0,0,BB,PRT,...,0,0,0,4,No Deposit,0,Transient,0,2015-07-01,2015-07-01
8,Resort Hotel,1,85,0,3,2,0.0,0,BB,PRT,...,0,0,0,0,No Deposit,0,Transient,1,2015-05-06,2015-07-01
9,Resort Hotel,1,75,0,3,2,0.0,0,HB,PRT,...,0,0,0,0,No Deposit,0,Transient,0,2015-04-22,2015-07-01
11,Resort Hotel,0,35,0,4,2,0.0,0,HB,PRT,...,0,0,0,0,No Deposit,0,Transient,0,2015-07-05,2015-07-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2,5,2,0.0,0,BB,otros,...,0,0,0,0,No Deposit,0,Transient,0,2017-09-06,2017-08-30
119386,City Hotel,0,102,2,5,3,0.0,0,BB,FRA,...,0,0,0,0,No Deposit,0,Transient,2,2017-09-07,2017-08-31
119387,City Hotel,0,34,2,5,2,0.0,0,BB,DEU,...,0,0,0,0,No Deposit,0,Transient,4,2017-09-07,2017-08-31
119388,City Hotel,0,109,2,5,2,0.0,0,BB,GBR,...,0,0,0,0,No Deposit,0,Transient,0,2017-09-07,2017-08-31
119389,City Hotel,0,205,2,7,2,0.0,0,HB,DEU,...,0,0,0,0,No Deposit,0,Transient,2,2017-09-07,2017-08-29

In [128]:
poca_antelacion = df[((df["is_canceled"] == 1) & (df['arrival_date'] - df['reservation_status_date'] <= pd.Timedelta(days=15)) | ((df["is_canceled"] == 0) & (df['lead_time'] <= 15)))]

In [129]:
poca_antelacion

,hotel,is_canceled,lead_time,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,...,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,deposit_type,days_in_waiting_list,customer_type,total_of_special_requests,reservation_status_date,arrival_date
2,Resort Hotel,0,7,0,1,1,0.0,0,BB,GBR,...,0,0,0,0,No Deposit,0,Transient,0,2015-07-02,2015-07-01
3,Resort Hotel,0,13,0,1,1,0.0,0,BB,GBR,...,0,0,0,0,No Deposit,0,Transient,0,2015-07-02,2015-07-01
4,Resort Hotel,0,14,0,2,2,0.0,0,BB,GBR,...,0,0,0,0,No Deposit,0,Transient,1,2015-07-03,2015-07-01
5,Resort Hotel,0,14,0,2,2,0.0,0,BB,GBR,...,0,0,0,0,No Deposit,0,Transient,1,2015-07-03,2015-07-01
6,Resort Hotel,0,0,0,2,2,0.0,0,BB,PRT,...,0,0,0,0,No Deposit,0,Transient,0,2015-07-03,2015-07-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119270,City Hotel,0,0,0,3,2,1.0,0,BB,otros,...,0,0,0,1,No Deposit,0,Transient,2,2017-09-01,2017-08-29
119304,City Hotel,0,4,0,3,1,0.0,0,BB,otros,...,0,0,0,1,No Deposit,0,Transient,0,2017-09-02,2017-08-30
119312,City Hotel,0,4,0,3,2,0.0,0,No_meal,FRA,...,0,0,0,0,No Deposit,0,Transient,1,2017-09-03,2017-08-31
119316,City Hotel,0,1,0,3,2,0.0,0,BB,GBR,...,0,0,0,0,No Deposit,0,Transient,1,2017-09-03,2017-08-31
119324,City Hotel,0,8,0,3,2,0.0,0,BB,otros,...,0,0,0,0,No Deposit,0,Transient,0,2017-09-03,2017-08-31

In [131]:
print(mucha_antelacion['is_canceled'].value_counts())
print(poca_antelacion['is_canceled'].value_counts())

0    51171
1    33902
Name: is_canceled, dtype: int64
0    23574
1    10251
Name: is_canceled, dtype: int64